http:
  host: 'localhost'
  port: 9999
  prefix: 'api'

mysql:
  host: 'gz-cynosdbmysql-grp-q8nof5dn.sql.tencentcdb.com'
  port: 27886
  database: 'lingmengcan'
  username: 'lingmengcan'
  password: 'lingmengcan-AI(9'
  charset: 'utf8'

mongodb:
  db: 'mongodb://localhost:27017/lingmengcan'

chromadb:
  db: 'http://localhost:9000'

files:
  destination: 'upload-files'
  aigc: 'aigc-files'

stablediffusion:
  apiUrl: 'http://localhost:7861'
